stamped: false
inputs:
  linear:
    x: axis_left_y
    y: axis_left_x
    z: axis_r2 - axis_l2
  angular:
    x: -axis_right_x
    y: axis_right_y
#z: button_l1 - button_r1
    z: axis_left_x
scales:
  linear:
    # Default scale is 1.0
    x: 0.2
    y: 0.2
    z: 2.0
  angular:
    x: 0.3
    y: 0.3
    z: 0.3 


